repos:
  - repo: local
    hooks:
      - id: python-linting
        name: python-linting
        entry: task lint
        language: system
        types: [python]

      - id: python-testing
        name: python-testing
        entry: task test
        language: system
        types: [python]
